### ISSUE TITLE
Can`t install

### ISSUE THREAD

**Issue by semasping** [wikimedia/composer-merge-plugin#183]
Used in octobercms.

Problem 1
    - Installation request for wikimedia/composer-merge-plugin dev-master -> satisfiable by wikimedia/composer-merge-plugin[dev-master].
    - wikimedia/composer-merge-plugin dev-master requires php >=7.2.0 -> your PHP version (7.3.12) overridden by "config.platform.php" version (7.0.8) does not satisfy that requirement.

OR

Problem 1
    - Installation request for wikimedia/composer-merge-plugin dev-master -> satisfiable by wikimedia/composer-merge-plugin[dev-master].
    - wikimedia/composer-merge-plugin dev-master requires php >=7.2.0 -> your PHP version (7.2.25) overridden by "config.platform.php" version (7.0.8) does not satisfy that requirement.

**Comment by bd808** [comment]
@semasping the error looks to be on your side and specifically that you are following dev-master and that the PHP version requirements there (>=7.2.0) are now greater than the apparent PHP version in your install environment (7.0.8).

Maybe try using https://github.com/wikimedia/composer-merge-plugin/releases/tag/v1.4.1 instead of dev-master?

**Comment by semasping** [comment]
7.0.8 it was written in composer.json.
current php-cli version is 7.2.25

it does not matter. I will wait for an official revision from the octobercms

thx

**Comment by semasping** [comment]
Developers of the OctoberCMS lock version of the library on 1.4.1.
https://github.com/octobercms/october/issues/5024
