### ISSUE TITLE
exists successfully after only half the work done

### ISSUE THREAD

**Issue by JanZerebecki** [wikimedia/composer-merge-plugin#34]
Running composer with the merge plugin just exits successfully (return 0) with only half the work done. I need to run it a second time to finish the work.

Example: https://integration.wikimedia.org/ci/job/mwext-WikidataQuality-repo-tests-mysql-hhvm/164/consoleFull (search for composer update and see were on the second invocation it still has more work to do).

**Comment by legoktm** [comment]
The first "composer update" installs the plugin, and the second one runs the plugin to fetch the dependencies.

**Comment by JeroenDeDauw** [comment]
Indeed, what @legoktm said. That is still annoying though. If anyone has thoughts on how to avoid that in a sane way, I'd be very interested in hearing them.

**Comment by bd808** [comment]
I've looked at this but it's really not fixable in the plugin. Composer would have to have some mechanism to see that a new plugin is being installed in vendor and then reload itself once the classes are downloaded and added to the autoloader. The chicken is still inside the egg at the end of the first execution. I don't think that there is even any way for the plugin to recognize that it has just be installed and prompt the user to run Composer a second time because of this.

**Comment by JeroenDeDauw** [comment]
I summon the great Composer wizard @Seldaek

**Comment by Seldaek** [comment]
We have discussed this at length for another plugin use case and it is really hard to fix in a clean (read: not having side effects on everyone else) way. 

It seems to me like if you installed extensions as composer packages their dependencies would be resolved automatically and you wouldn't need this plugin at all. I understand that transitioning large communities isn't easy, but is this the end goal at all? I would think of the plugin as a transitive thing that's imperfect but helps smoothen the process.

As for detecting if the plugin was just installed.. I think if it registers a post-package-install listener, it might well get called just after the plugin is installed and enabled, so you could detect that and warn users. Or possibly you could even (**warning possibly dirty idea coming**) detect that, and in  a post-install-cmd/post-update-cmd listener load up the Composer\Installer class and re-run an install/update yourself from within the plugin.

**Comment by bd808** [comment]
> It seems to me like if you installed extensions as composer packages their dependencies would be resolved automatically and you wouldn't need this plugin at all. I understand that transitioning large communities isn't easy, but is this the end goal at all?

Moving all extension installations to Composer is a closed issue as far as I know. We discussed it at length, found the options wanting and are moving on with our lives. See https://phabricator.wikimedia.org/T467 and https://github.com/composer/composer/issues/4109 for some of the discussion. Let's not debate the concept further here in a isolated setting.

> As for detecting if the plugin was just installed.. I think if it registers a post-package-install listener, it might well get called just after the plugin is installed and enabled, so you could detect that and warn users.

I'll see if I can find a bit of time to test this theory out. It would be nice to be able to at least log a warning in first install.

The unexamined third option would be to upstream the merge feature into Composer itself and abandon use of the plugin hack. I wanted to start out as a plugin to prove that it could be done but maybe it is time to open that discussion upstream? The functionality here is similar to the inheritance support being discussed in https://github.com/composer/composer/issues/183 but switch around to the point of view of extending a common composer.json file rather than inheriting from a parent. In an inheritance model we would still have the dirty diff problem for local composer.json changes that differed from the upstream.

**Comment by Seldaek** [comment]
Yes merging that in is another way of course, but I am not sure what the implications would be with regard to things like the lock file.

Did you consider my last proposal? I think it could actually work even though it sounds a bit mad it's not that dirty in practice.

**Comment by bd808** [comment]
> Did you consider my last proposal? I think it could actually work even though it sounds a bit mad it's not that dirty in practice.

I just started messing with it, but yeah I think there may be something workable. I have confirmed that a handler installed by the plugin for PackageEvents::POST_PACKAGE_INSTALL will fire when the plugin package itself is initially installed.

**Comment by hashar** [comment]
Thanks folks for dealing with this!

**Comment by thewilkybarkid** [comment]
Could this be reviewed? I've just discovered that on Travis we're getting an update straight after our install, so we end up using versions that we're not expecting. We'll have to run `composer install` again to force it to revert back to the versions that we actually wanted.

**Comment by thewilkybarkid** [comment]
So I'm having to go for something like:

```bash
cp composer.lock composer.lock.orig
composer install --no-interaction
mv composer.lock.orig composer.lock
composer install --no-interaction
```

**Comment by bd808** [comment]
@thewilkybarkid Could you split out a new bug report for this? It sounds like the use of `$installer->setUpdate(true);` in `onPostInstallOrUpdate` is causing you problems. I'm assuming that you are using Composer with a versioned composer.lock file and permissive dependency version numbers in your composer.json file. Would it also be correct to assume that the versioned composer.lock file includes `wikimedia/composer-merge-plugin`?
