### ISSUE TITLE
Update on initial install

### ISSUE THREAD

**Issue by thewilkybarkid** [wikimedia/composer-merge-plugin#50]
See https://github.com/wikimedia/composer-merge-plugin/issues/34#issuecomment-126305530

When using Travis CI or using a deployment tool such as Capifony/Capistrano (or whenever installing dependencies for the first time), the plugin runs a `composer update` after your `composer install`, causing any newer versions to be installed (contrary to what's in your lock file).

As it stands, a second `composer install` has to be run to force it back to the expected state.

**Comment by bd808** [comment]
I wonder if there is a way for the plugin to determine if a `composer.lock` file was present at the time `composer install` was executed?

The core issue that the use of `$installer->setUpdate(true);` attempts to work around is that in a clean install (no vendor, no composer.lock) the first invocation of `composer update` or `composer install` writes a `composer.lock` **before** `onPostInstallOrUpdate()` triggers the second installer run to actually process the merged composer.json files. Since there is a `composer.lock` at the time of the second invocation, if any files are merged Composer will halt with an error "Your requirements could not be resolved to an installable set of packages." Running `composer update` will fix this and actually install the packages.

I have tested and found that if a `composer.lock` including all dependencies is present, an initial `composer install` which installs the plugin will succeed.

**Comment by bd808** [comment]
@thewilkybarkid Can you test out the changes in #54 and see if they fix your problem?

**Comment by thewilkybarkid** [comment]
@bd808 :+1: I removed my `vendor` folder, changed my lock file so use your commit, ran `composer install` and no update occurred.
