### ISSUE TITLE
Question: why "Skipping duplicate" messages?

### ISSUE THREAD

**Issue by claudio-silva** [wikimedia/composer-merge-plugin#66]
When running `composer update -vvv` I always a messages like the one below, for each included `composer.json`:
```
[merge-plugin] Skipping duplicate composer.local.json...
```
None of those files have duplicate references anywhere.

Is this normal and expected?
What does it mean?

**Comment by bd808** [comment]
This is generally expected behavior. `MergePlugin::onInstallUpdateOrDump` is called two times in response to a `composer update` call. On the second call this "skipping ..." message will be emitted as the internal logic asserts that each file in the list of included files has already been merged into the root package configuration.

**Comment by claudio-silva** [comment]
Thanks for the clarification.
May I suggest you change the message to something less prone to cause confusion and/or doubt for the user?
Ex:
```
Rechecking xxx...
Already merged.
```
I know it's a little detail, but it may prevent further questions similar to mine from other users.

By the way, thank you for this amazing plugin!
It's so damn useful I can't understand why the Composer developers don't merge it in!... ;-)
