### ISSUE TITLE
does post-update-cmd get merged?

### ISSUE THREAD

**Issue by coding-sunshine** [wikimedia/composer-merge-plugin#68]
Hi, I was wondering that there is no mention whether the events get merged or not?
I was trying post-update-cmd to be merged but it doesn't.

**Comment by bd808** [comment]
We so not currently attempt to merge the "scripts" section of any included files with the root project. Doing so would be tricky to get right for all script events without some upstream changes for Composer itself. Our plugin itself is activated by hooking the "pre-install-cmd", "pre-update-cmd" and "pre-autoload-dump" script hooks. This means that one of these events would have already been sent by Composer before we could merge new handler registrations in to the root config.

We could possibly hook the "command" plugin event and be in a position to have merged changes present for most of the events Composer dispatches.

**Comment by coding-sunshine** [comment]
I think, "command" plugin event can be a great addition, I will also try if I can put PR for that soon.

**Comment by stevector** [comment]
There's a [scriptsdev](https://github.com/neronmoon/scriptsdev) plugin that uses the `activate` method on PluginInterface to call 

```
$composer->getPackage()->setScripts($scripts);
```
https://github.com/neronmoon/scriptsdev/blob/master/src/Plugin.php

@bd808, what do you think of using the same means to merge scripts? I suggest using that method because I don't see a way to call `setScripts()` from the "command" event.

**Comment by bd808** [comment]
See #135 and #136
