### ISSUE TITLE
Option to not merge require-dev sections

### ISSUE THREAD

**Issue by legoktm** [wikimedia/composer-merge-plugin#85]
For MediaWiki extensions, "require" contains the dependencies that should be merged into the main MediaWiki core vendor bundle, while "require-dev" are for the local repository and not meant to be merged/used by MediaWiki. It becomes problematic when different extensions have incompatible development dependency versions.

[IRC discussion](http://bots.wmflabs.org/~wm-bot/logs/%23mediawiki-core/20151028.txt)

**Comment by JanZerebecki** [comment]
Note that this won't work as described here because a phpunit run requires the dev dependencies and the phpunit tests of all extensions are supposed to be able to run together.

**Comment by bd808** [comment]
> Note that this won't work as described here because a phpunit run requires the dev dependencies and the phpunit tests of all extensions are supposed to be able to run together.

Can you be more specific about where this will cause problems in the general sense @JanZerebecki? 

Opening a new bug would be the right thing to do if you have a specific concern. If your concern is about composer-merge-plugin in general then I would suggest filing a bug here and if you are concerned about potential problems in a particular project that uses composer-merge-plugin (eg MediaWiki) then I would suggest you file the bug with that project.

**Comment by JanZerebecki** [comment]
This task states a problem (with how e.g. phpunit is specified with an exact version as require-dev in mediawiki and extensions at the same time and thus the version can not be different when those dependencies are merged) and a solution. There is no problem with the solution in the general sense. This solution just won't work for the specified problem, at least as far as I understood. Because we can not both not merge require-dev and run phpunit tests from an extension.

My comment was just a note and requires no action => no new task, at least from my side.
